version: "3"
services:

  web36:
    build:
      context: .
      dockerfile: Dockerfile36
    entrypoint: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=app
      - FLASK_RUN_PORT=5000
    ports:
      - "5000:5000"

  web37:
    build:
      context: .
      dockerfile: Dockerfile37
    entrypoint: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=app
      - FLASK_RUN_PORT=5000
    ports:
      - "5000:5000"
