version: "3"
services:

  web36:
    build:
      context: .
      dockerfile: Dockerfile36
    entrypoint: flask run --host=0.0.0.0 --port=5000
    environment:
      - FLASK_APP=app
    ports:
      - "5000:5000"

  web37:
    build:
      context: .
      dockerfile: Dockerfile37
    entrypoint: flask run --host=0.0.0.0 --port=5050
    environment:
      - FLASK_APP=app
    ports:
      - "5050:5050"
